//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPGTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.MPGs = new HashSet<MPG>();
            this.OilChanges = new HashSet<OilChanges>();
        }
    
        public int Id { get; set; }
        public string Owner { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Year { get; set; }
    
        public virtual ICollection<MPG> MPGs { get; set; }
        public virtual ICollection<OilChanges> OilChanges { get; set; }
    }
}
