//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPGTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPG
    {
        public int Id { get; set; }
        public string GallonsPurchased { get; set; }
        public string MilesTraveled { get; set; }
        public string DateOfFillUp { get; set; }
        public int CarId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
